# Deep Learning with PyTorch: A 60 Minute Blitz

## What is PyTorch?

It's a Python-based scientific computing package targeted at two sets of audiences:

- A replacement for NumPy to use the power of GPUs
- A deep learning research platform that provides maximum flexibility and speed

### Getting started

#### Tensors

Tensors are similar to NumPy's ndarrays, with the addition being that tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

# Construct a 5x3 matrix, uninitialised
x = torch.Tensor(5, 3)
print(x)


-1.4070e+21  4.5845e-41 -1.4070e+21
 4.5845e-41         nan  3.0704e-41
 4.4721e+21  1.6647e-41  6.7262e-44
 0.0000e+00  6.7262e-44  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
[torch.FloatTensor of size 5x3]



In [2]:
# Construct a randomly initialised matrix:
x = torch.rand(5, 3)
print(x)


 0.6140  0.2486  0.6760
 0.1794  0.0191  0.8693
 0.6072  0.2850  0.5800
 0.6603  0.6227  0.5303
 0.4463  0.0649  0.3081
[torch.FloatTensor of size 5x3]



In [3]:
# Get the size of the matrix
print(x.size())

torch.Size([5, 3])


> `torch.Size` is in fact a tuple, so it supports all tuple operations.

#### Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

First syntax:

In [4]:
y = torch.rand(5, 3)
print(x + y)


 1.3821  0.3726  1.2041
 0.6460  0.3888  1.0947
 1.4570  0.7736  1.3610
 1.5324  1.2661  1.4413
 0.6205  0.9907  1.2872
[torch.FloatTensor of size 5x3]



Second syntax:

In [5]:
print(torch.add(x, y))


 1.3821  0.3726  1.2041
 0.6460  0.3888  1.0947
 1.4570  0.7736  1.3610
 1.5324  1.2661  1.4413
 0.6205  0.9907  1.2872
[torch.FloatTensor of size 5x3]



Addition: providing an output tensor as argument

In [6]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.3821  0.3726  1.2041
 0.6460  0.3888  1.0947
 1.4570  0.7736  1.3610
 1.5324  1.2661  1.4413
 0.6205  0.9907  1.2872
[torch.FloatTensor of size 5x3]



Addition: in-place

In [7]:
# This adds x to y
y.add_(x)
print(y)


 1.3821  0.3726  1.2041
 0.6460  0.3888  1.0947
 1.4570  0.7736  1.3610
 1.5324  1.2661  1.4413
 0.6205  0.9907  1.2872
[torch.FloatTensor of size 5x3]



> Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()` will change `x`.

You can use standard NumPy-like indexing with all bells and whistles!

In [8]:
print(x[:, 1])


 0.2486
 0.0191
 0.2850
 0.6227
 0.0649
[torch.FloatTensor of size 5]



If you want to resize or reshape a tensor, you can use `torch.view`:

In [9]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # The size '-1' is inferred from the other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers etc. are described [here](http://pytorch.org/docs/master/torch.html).

### NumPy Bridge

Converting a Torch tensor to a NumPy array and viceversa is a breeze. The Torch tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

#### Converting a Torch tensor to a NumPy array

In [10]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [11]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the NumPy array changed in value:

In [12]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[2. 2. 2. 2. 2.]


#### Converting a NumPy array to a Torch tensor

See how changing the NumPy array changes the Torch tensor automatically:

In [13]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the tensors on the CPU (except a CharTensor) support converting to NumPy and back.

### CUDA Tensors

Tensors can be moved onto the GPU using the `.cuda` method.

In [16]:
# We run this cell only if CUDA is available
x = torch.rand(5, 3)
y = torch.rand(5, 3)

if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    print(x + y)


 0.1190  1.5981  1.0272
 1.0945  1.3571  1.1249
 1.2283  1.5060  0.4339
 0.7411  0.6635  0.5034
 1.5045  1.1866  1.8876
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]

